services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: surfsup
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    networks:
      - laravel

  nginx:
    image: nginx:1.25
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    ports:
      - '3360:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
