version: '3.8'

services:
  app:
    image: bitnami/laravel:latest # Replace with your actual image or build context if needed
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - '${APP_PORT:-8084}:80'
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: '${APP_KEY}'
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    networks:
      - laravel

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  laravel:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
